QUESTIONS = [
    # ─────────────────────────────────────────────
    # CATEGORY: QA Fundamentals
    # ─────────────────────────────────────────────
    {
        "question": "What is the difference between severity and priority in bug tracking?",
        "options": [
            "Severity = urgency; Priority = system impact",
            "Severity = system impact; Priority = urgency to fix",
            "They mean the same thing",
            "Severity applies to UI bugs only",
        ],
        "answer": "Severity = system impact; Priority = urgency to fix",
        "category": "QA Fundamentals",
        "explanation": "A critical crash in a never-used feature is high severity but low priority.",
    },
    {
        "question": "What is the test pyramid?",
        "options": [
            "E2E tests (base) → Integration (middle) → Unit (top)",
            "Unit tests (base) → Integration tests (middle) → E2E tests (top)",
            "Manual tests (base) → Automated (top)",
            "Smoke tests (base) → Regression (top)",
        ],
        "answer": "Unit tests (base) → Integration tests (middle) → E2E tests (top)",
        "category": "QA Fundamentals",
        "explanation": "Unit tests are fast and numerous; E2E are slow and few. Pyramid shape = many fast tests, few slow ones.",
    },
    {
        "question": "What is a flaky test?",
        "options": [
            "A test that always fails",
            "A test with poor naming",
            "A test that non-deterministically passes and fails without code changes",
            "A test that takes too long",
        ],
        "answer": "A test that non-deterministically passes and fails without code changes",
        "category": "QA Fundamentals",
        "explanation": "Causes include timing issues, external dependencies, shared state, and race conditions.",
    },
    {
        "question": "What makes a good bug report?",
        "options": [
            "Just a description of what went wrong",
            "Title, steps to reproduce, expected result, actual result, severity, environment",
            "A screenshot only",
            "The developer's name and the fix suggestion",
        ],
        "answer": "Title, steps to reproduce, expected result, actual result, severity, environment",
        "category": "QA Fundamentals",
        "explanation": "A complete bug report lets anyone reproduce the issue independently.",
    },
    {
        "question": "What is the difference between verification and validation?",
        "options": [
            "They are the same concept",
            "Verification = building it right (spec); Validation = building the right thing (user needs)",
            "Verification happens after release; Validation before",
            "Validation = unit tests; Verification = E2E tests",
        ],
        "answer": "Verification = building it right (spec); Validation = building the right thing (user needs)",
        "category": "QA Fundamentals",
        "explanation": "Verification checks process; validation checks the product against real-world needs.",
    },
    {
        "question": "What is shift-left testing?",
        "options": [
            "Running tests from left to right in a pipeline",
            "Involving QA earlier in development (at requirements/design stage)",
            "Moving tests to the left side of the screen",
            "Doing unit tests after E2E tests",
        ],
        "answer": "Involving QA earlier in development (at requirements/design stage)",
        "category": "QA Fundamentals",
        "explanation": "Shift-left finds issues earlier when they are cheaper to fix.",
    },
    {
        "question": "What is exploratory testing?",
        "options": [
            "Following a pre-written test script exactly",
            "Unscripted testing where the tester actively explores the system",
            "Testing the same scenarios repeatedly",
            "Automated regression testing",
        ],
        "answer": "Unscripted testing where the tester actively explores the system",
        "category": "QA Fundamentals",
        "explanation": "Exploratory testing relies on the tester's intuition and experience to find unexpected issues.",
    },
    {
        "question": "What is boundary value analysis?",
        "options": [
            "Testing only the middle range of values",
            "Testing random values",
            "Testing at minimum, maximum, just below min, and just above max",
            "Testing with null values only",
        ],
        "answer": "Testing at minimum, maximum, just below min, and just above max",
        "category": "QA Fundamentals",
        "explanation": "Most bugs occur at the edges of valid ranges, not in the middle.",
    },
    {
        "question": "What is the difference between a test case and a test scenario?",
        "options": [
            "They mean the same thing",
            "Scenario = specific steps; Test case = high-level description",
            "Scenario = high-level situation; Test case = specific steps + expected result",
            "Test cases are manual; scenarios are automated",
        ],
        "answer": "Scenario = high-level situation; Test case = specific steps + expected result",
        "category": "QA Fundamentals",
        "explanation": "One scenario can contain multiple test cases covering different variations.",
    },
    {
        "question": "In the FIRMS framework, what does 'R' stand for?",
        "options": [
            "Requirements",
            "Roles",
            "Risks — areas where failure has the greatest business impact",
            "Rules",
        ],
        "answer": "Risks — areas where failure has the greatest business impact",
        "category": "QA Fundamentals",
        "explanation": "FIRMS = Functionality, Inputs, Risks, Misuse, System Impact.",
    },
    # ─────────────────────────────────────────────
    # CATEGORY: Tufin & Networking
    # ─────────────────────────────────────────────
    {
        "question": "What is the main purpose of the Tufin platform?",
        "options": [
            "Build new firewalls",
            "Centrally manage and automate firewall/network security policies across hybrid environments",
            "Monitor end-user activity",
            "Develop mobile applications",
        ],
        "answer": "Centrally manage and automate firewall/network security policies across hybrid environments",
        "category": "Tufin & Networking",
        "explanation": "Tufin orchestrates security policy across complex, multi-vendor, multi-cloud environments.",
    },
    {
        "question": "Why does firewall rule ORDER matter?",
        "options": [
            "Rule order doesn't matter — all rules are evaluated",
            "Alphabetical order is used for evaluation",
            "The first matching rule is applied (top-down). Wrong order can block allowed traffic.",
            "The last rule always wins",
        ],
        "answer": "The first matching rule is applied (top-down). Wrong order can block allowed traffic.",
        "category": "Tufin & Networking",
        "explanation": "If a broad 'deny all' rule appears before a specific 'allow' rule, traffic is blocked.",
    },
    {
        "question": "What is RBAC?",
        "options": [
            "Remote Backend API Control",
            "Role-Based Access Control — users are assigned roles with specific permissions",
            "Rule-Based Authentication Code",
            "Real-time Backup and Copy",
        ],
        "answer": "Role-Based Access Control — users are assigned roles with specific permissions",
        "category": "Tufin & Networking",
        "explanation": "RBAC controls what actions users can perform based on their assigned role.",
    },
    {
        "question": "Why must RBAC be tested at the API level, not just the UI?",
        "options": [
            "API testing is faster",
            "Users can bypass the UI and call the API directly — the backend must enforce permissions independently",
            "UI testing is unreliable",
            "APIs are more important than UIs",
        ],
        "answer": "Users can bypass the UI and call the API directly — the backend must enforce permissions independently",
        "category": "Tufin & Networking",
        "explanation": "A user might not see the 'edit' button in the UI but could still send an edit request directly via Postman.",
    },
    {
        "question": "What does HTTP 403 Forbidden indicate in RBAC testing?",
        "options": [
            "The server is down",
            "The request syntax is wrong",
            "The user is not logged in",
            "The user is authenticated but does not have permission for this action",
        ],
        "answer": "The user is authenticated but does not have permission for this action",
        "category": "Tufin & Networking",
        "explanation": "401 = not authenticated. 403 = authenticated but not authorized.",
    },
    {
        "question": "What is the difference between a Firewall Event Log and an Audit Log?",
        "options": [
            "They are the same thing",
            "Firewall Events = network traffic actions; Audit Log = user/admin actions on the system",
            "Audit logs are more detailed",
            "Firewall Events are stored in the cloud",
        ],
        "answer": "Firewall Events = network traffic actions; Audit Log = user/admin actions on the system",
        "category": "Tufin & Networking",
        "explanation": "Event logs track traffic. Audit logs track administrative changes (who changed what rule, when).",
    },
    {
        "question": "What does QA test in an Admin Permissions screen?",
        "options": [
            "That all checkboxes are visible",
            "That the page loads fast",
            "That each permission checkbox is correctly enforced at both the UI and API level for each role",
            "That the screen uses the correct font",
        ],
        "answer": "That each permission checkbox is correctly enforced at both the UI and API level for each role",
        "category": "Tufin & Networking",
        "explanation": "You must verify that checking/unchecking permissions actually changes what users can do — not just the UI state.",
    },
    {
        "question": "What is performance testing in the context of a Tufin firewall policy list?",
        "options": [
            "Testing the speed of physical network cables",
            "Testing load time, filter/search speed, and UI rendering with thousands of rules",
            "Running code benchmarks",
            "Testing the speed of policy installation",
        ],
        "answer": "Testing load time, filter/search speed, and UI rendering with thousands of rules",
        "category": "Tufin & Networking",
        "explanation": "Enterprise customers may have thousands of firewall rules. Performance must hold under that scale.",
    },
    {
        "question": "What is the purpose of a Detection & Response dashboard?",
        "options": [
            "Configure new firewall rules",
            "Monitor security alerts, track cases/incidents, understand severity and status",
            "Manage user accounts",
            "Generate billing reports",
        ],
        "answer": "Monitor security alerts, track cases/incidents, understand severity and status",
        "category": "Tufin & Networking",
        "explanation": "Detection & Response dashboards help security teams triage and investigate incidents.",
    },
    {
        "question": "What should you validate FIRST on a metrics dashboard?",
        "options": [
            "Button colors and fonts",
            "Page load time",
            "Data accuracy — totals must match the breakdown (e.g., open + acknowledged + closed = total)",
            "Number of columns in the table",
        ],
        "answer": "Data accuracy — totals must match the breakdown (e.g., open + acknowledged + closed = total)",
        "category": "Tufin & Networking",
        "explanation": "A monitoring tool is only useful if the data it shows is correct and consistent.",
    },
    # ─────────────────────────────────────────────
    # CATEGORY: Check Point Networking
    # ─────────────────────────────────────────────
    {
        "question": "What are the two main architectural components of Check Point?",
        "options": [
            "Firewall and Router",
            "Management Server and Security Gateway",
            "Client and Server",
            "SmartConsole and SmartDashboard",
        ],
        "answer": "Management Server and Security Gateway",
        "category": "Check Point Networking",
        "explanation": "Management Server = policy management. Security Gateway = traffic enforcement. Two separate roles.",
    },
    {
        "question": "What is the correct order of the Check Point policy lifecycle?",
        "options": [
            "Publish → Edit → Install → Verify",
            "Edit rule → Save → Publish → Install Policy → Verify",
            "Install → Publish → Edit → Verify",
            "Create → Deploy → Monitor → Edit",
        ],
        "answer": "Edit rule → Save → Publish → Install Policy → Verify",
        "category": "Check Point Networking",
        "explanation": "This order is critical — skipping Publish or Install means the gateway never receives the change.",
    },
    {
        "question": "What does 'Publish' do in Check Point SmartConsole?",
        "options": [
            "Deploys rules to the gateway immediately",
            "Commits pending rule changes to the management database (makes them visible to all admins)",
            "Saves changes locally only",
            "Sends an email notification",
        ],
        "answer": "Commits pending rule changes to the management database (makes them visible to all admins)",
        "category": "Check Point Networking",
        "explanation": "Without publishing, changes exist only in your editing session and are not visible to others.",
    },
    {
        "question": "How does a firewall evaluate packets against its rule base?",
        "options": [
            "It evaluates all rules and picks the best match",
            "It evaluates rules top-down and the first matching rule wins",
            "It evaluates rules bottom-up and the last matching rule wins",
            "It randomly selects a rule to apply",
        ],
        "answer": "It evaluates rules top-down and the first matching rule wins",
        "category": "Check Point Networking",
        "explanation": "Firewalls use first-match-wins logic. As soon as a matching rule is found, its action is applied and evaluation stops.",
    },
    {
        "question": "What five fields does each firewall rule typically specify?",
        "options": [
            "Username, Password, Protocol, Time, Priority",
            "Source, Destination, Service/Port, Action (Allow/Block), and Logging/Track",
            "IP Address, MAC Address, VLAN, QoS, and NAT",
            "Interface, Zone, Application, User, and Schedule",
        ],
        "answer": "Source, Destination, Service/Port, Action (Allow/Block), and Logging/Track",
        "category": "Check Point Networking",
        "explanation": "Every rule defines: Source (who), Destination (where), Service/Port (what), Action (allow or block), and Track (how to log it).",
    },
    {
        "question": "A deny-all rule is placed at the TOP of the rule base, above all allow rules. What happens?",
        "options": [
            "The allow rules below it still work normally",
            "All traffic is denied because the deny-all matches first before any allow rule is reached",
            "Check Point ignores the deny-all and continues evaluating",
            "Only outbound traffic is denied",
        ],
        "answer": "All traffic is denied because the deny-all matches first before any allow rule is reached",
        "category": "Check Point Networking",
        "explanation": "Rule order is critical. A deny-all at the top will match every packet before any specific allow rule below it can be reached.",
    },
    {
        "question": "A policy change was published and installation appeared to succeed, but traffic behavior has not changed. What is the most likely cause?",
        "options": [
            "The Management Server needs to be restarted",
            "The policy was published but Install Policy was never actually run against the correct gateway",
            "SmartLog needs to be cleared before changes take effect",
            "The change must be approved by a second admin",
        ],
        "answer": "The policy was published but Install Policy was never actually run against the correct gateway",
        "category": "Check Point Networking",
        "explanation": "Publishing commits changes to the management database. Until Install Policy runs and pushes the compiled policy to the gateway, it continues enforcing the old policy.",
    },
    {
        "question": "Policy was installed successfully but some traffic is still blocked despite a new allow rule. What should you check?",
        "options": [
            "Reboot the gateway to apply all changes",
            "Check that the rule conditions exactly match the traffic: correct source IP, destination IP, port, and that the allow rule is positioned above any deny rule covering the same traffic",
            "Delete the old rules and start fresh",
            "Reinstall the Check Point gateway software",
        ],
        "answer": "Check that the rule conditions exactly match the traffic: correct source IP, destination IP, port, and that the allow rule is positioned above any deny rule covering the same traffic",
        "category": "Check Point Networking",
        "explanation": "Common causes: wrong IP/port in the rule, or a more general deny rule sitting above the allow rule. Use SmartLog to see which rule is actually matching the traffic.",
    },
    {
        "question": "What is the difference between SMC and CMA in Check Point?",
        "options": [
            "SMC is older; CMA is newer",
            "SMC = single-domain management; CMA = multi-domain management for large enterprises",
            "They are the same product",
            "SMC is for gateways; CMA is for management servers",
        ],
        "answer": "SMC = single-domain management; CMA = multi-domain management for large enterprises",
        "category": "Check Point Networking",
        "explanation": "CMA (Customer Management Add-on) allows one platform to manage multiple independent security domains.",
    },
    {
        "question": "What is the Cleanup Rule in a Check Point policy?",
        "options": [
            "An automated rule that removes expired rules from the policy",
            "The last explicit rule in the policy — typically 'Block All' with logging enabled, placed before the implicit deny so that dropped traffic is actually logged",
            "A rule that clears connection state tables on the gateway",
            "A rule that removes duplicate or conflicting entries automatically",
        ],
        "answer": "The last explicit rule in the policy — typically 'Block All' with logging enabled, placed before the implicit deny so that dropped traffic is actually logged",
        "category": "Check Point Networking",
        "explanation": "The implicit deny blocks traffic but does NOT log it. The Cleanup Rule is an explicit Block All with logging, placed just above the implicit deny, so admins can see what was denied.",
    },
    # ─────────────────────────────────────────────
    # CATEGORY: Java & Debugging
    # ─────────────────────────────────────────────
    {
        "question": 'Why is (status == "ERROR") wrong in Java?',
        "options": [
            "It is correct Java syntax",
            "== compares object references, not string content. Use .equals() instead.",
            "It will throw a compilation error",
            "== works for strings shorter than 10 characters",
        ],
        "answer": "== compares object references, not string content. Use .equals() instead.",
        "category": "Java & Debugging",
        "explanation": "Two String objects with identical content may have different memory references. .equals() compares actual text.",
    },
    {
        "question": "What error does 'for (int i = 0; i <= array.length; i++)' cause?",
        "options": [
            "It works correctly",
            "ArrayIndexOutOfBoundsException — array indices are 0 to length-1",
            "NullPointerException",
            "StackOverflowError",
        ],
        "answer": "ArrayIndexOutOfBoundsException — array indices are 0 to length-1",
        "category": "Java & Debugging",
        "explanation": "The last valid index is array.length - 1. The <= causes one extra iteration beyond bounds.",
    },
    {
        "question": "The inverted counting bug: if(counts.containsKey(w)) { put(w,1) } else { put(w, get(w)+1) }. What is wrong?",
        "options": [
            "Nothing is wrong",
            "Logic is backwards — existing keys reset to 1; missing keys cause NullPointerException when calling get()",
            "The loop is wrong",
            "HashMap does not support containsKey",
        ],
        "answer": "Logic is backwards — existing keys reset to 1; missing keys cause NullPointerException when calling get()",
        "category": "Java & Debugging",
        "explanation": "When key EXISTS → should increment. When key MISSING → should initialize to 1. The branches are swapped.",
    },
    {
        "question": "The filter bug: if(!email.contains('@')) validEmails.add(email). What is wrong?",
        "options": [
            "The condition is correct",
            "The ! inverts the condition — it adds emails WITHOUT '@' (invalid ones) instead of valid ones",
            "The add() method is wrong",
            ".contains() does not work for characters",
        ],
        "answer": "The ! inverts the condition — it adds emails WITHOUT '@' (invalid ones) instead of valid ones",
        "category": "Java & Debugging",
        "explanation": "Remove the ! to correctly include only valid emails that contain '@'.",
    },
    {
        "question": "What Java data structure is best for counting word frequencies?",
        "options": [
            "ArrayList<String>",
            "HashMap<String, Integer>",
            "HashSet<String>",
            "int[]",
        ],
        "answer": "HashMap<String, Integer>",
        "category": "Java & Debugging",
        "explanation": "HashMap maps each word (key) to its count (value) with O(1) average lookup.",
    },
    {
        "question": "How do you find the first non-repeating element in a list?",
        "options": [
            "Sort the list and return the first element",
            "First pass: count frequencies with HashMap. Second pass: return first element with count == 1.",
            "Use a nested loop for comparison",
            "Use a HashSet and remove duplicates",
        ],
        "answer": "First pass: count frequencies with HashMap. Second pass: return first element with count == 1.",
        "category": "Java & Debugging",
        "explanation": "Two-pass approach is O(n) — more efficient than a nested loop O(n^2).",
    },
    {
        "question": 'What does this code do: for(String log : logs) { if(log.contains("ERROR")) count++; }',
        "options": [
            "Deletes error logs",
            "Counts log messages that contain the word 'ERROR'",
            "Extracts error messages into a new list",
            "Replaces ERROR with WARNING",
        ],
        "answer": "Counts log messages that contain the word 'ERROR'",
        "category": "Java & Debugging",
        "explanation": "This is a simple frequency filter pattern using string matching.",
    },
    {
        "question": "What is the 5-step framework for narrating code in a live interview?",
        "options": [
            "Read → Run → Debug → Commit → Deploy",
            "Describe → Identify issue → Explain why → Propose fix → Write the fix",
            "Plan → Code → Test → Review → Ship",
            "Import → Declare → Loop → Return → Print",
        ],
        "answer": "Describe → Identify issue → Explain why → Propose fix → Write the fix",
        "category": "Java & Debugging",
        "explanation": "Narrating your reasoning is as important as writing correct code in a live coding interview.",
    },
    {
        "question": "What should you do first in a live coding interview before writing any code?",
        "options": [
            "Start coding immediately to show speed",
            "Restate the problem in your own words and confirm you understand the goal",
            "Ask for hints",
            "Write all imports first",
        ],
        "answer": "Restate the problem in your own words and confirm you understand the goal",
        "category": "Java & Debugging",
        "explanation": "Confirming understanding prevents solving the wrong problem — a critical mistake.",
    },
    # ─────────────────────────────────────────────
    # CATEGORY: API, SQL & Linux
    # ─────────────────────────────────────────────
    {
        "question": "What is the difference between PATCH and PUT?",
        "options": [
            "They are identical",
            "PATCH updates specific fields; PUT replaces the entire resource",
            "PUT is for new resources; PATCH is for existing ones",
            "PATCH is faster than PUT",
        ],
        "answer": "PATCH updates specific fields; PUT replaces the entire resource",
        "category": "API, SQL & Linux",
        "explanation": "Use PATCH when you only want to change one or two fields of a large resource.",
    },
    {
        "question": "What does HTTP 201 Created mean?",
        "options": [
            "Request succeeded but nothing changed",
            "A new resource was successfully created",
            "The resource was updated",
            "The server is ready",
        ],
        "answer": "A new resource was successfully created",
        "category": "API, SQL & Linux",
        "explanation": "POST requests that create a resource should return 201 (not 200).",
    },
    {
        "question": "What is the difference between HTTP 401 and 403?",
        "options": [
            "They mean the same thing",
            "401 = not authenticated (who are you?); 403 = authenticated but not authorized (you can't do this)",
            "401 = server error; 403 = client error",
            "401 = missing data; 403 = invalid data",
        ],
        "answer": "401 = not authenticated (who are you?); 403 = authenticated but not authorized (you can't do this)",
        "category": "API, SQL & Linux",
        "explanation": "401 prompts the client to log in. 403 tells them they're logged in but forbidden.",
    },
    {
        "question": "What should you validate beyond the HTTP status code in API testing?",
        "options": [
            "Nothing — status code is sufficient",
            "Response body structure, field values, data types, response time, error messages",
            "Only the HTTP headers",
            "Only the response size",
        ],
        "answer": "Response body structure, field values, data types, response time, error messages",
        "category": "API, SQL & Linux",
        "explanation": "A 200 status with incorrect data is still a bug. Schema and value validation are critical.",
    },
    {
        "question": "What SQL clause filters rows BEFORE grouping?",
        "options": ["HAVING", "WHERE", "GROUP BY", "ORDER BY"],
        "answer": "WHERE",
        "category": "API, SQL & Linux",
        "explanation": "WHERE filters raw rows. HAVING filters after aggregation with GROUP BY.",
    },
    {
        "question": "What is the difference between INNER JOIN and LEFT JOIN?",
        "options": [
            "They are identical",
            "INNER JOIN returns matching rows from both tables; LEFT JOIN returns all rows from the left table",
            "LEFT JOIN is faster than INNER JOIN",
            "INNER JOIN only works on 2 tables",
        ],
        "answer": "INNER JOIN returns matching rows from both tables; LEFT JOIN returns all rows from the left table",
        "category": "API, SQL & Linux",
        "explanation": "LEFT JOIN includes unmatched rows from the left table with NULL for right-table columns.",
    },
    {
        "question": "How do you find duplicate values in SQL?",
        "options": [
            "SELECT DISTINCT col FROM table",
            "SELECT col, COUNT(*) FROM table GROUP BY col HAVING COUNT(*) > 1",
            "SELECT col FROM table WHERE col = col",
            "DELETE DUPLICATES FROM table",
        ],
        "answer": "SELECT col, COUNT(*) FROM table GROUP BY col HAVING COUNT(*) > 1",
        "category": "API, SQL & Linux",
        "explanation": "Group by the column, then filter for groups with more than one occurrence.",
    },
    {
        "question": "What does grep 'ERROR' app.log do?",
        "options": [
            "Deletes lines with ERROR",
            "Counts lines with ERROR",
            "Searches for and prints all lines in app.log containing 'ERROR'",
            "Replaces ERROR with WARNING",
        ],
        "answer": "Searches for and prints all lines in app.log containing 'ERROR'",
        "category": "API, SQL & Linux",
        "explanation": "grep is a powerful text search tool. grep -c counts matches; grep -v inverts the match.",
    },
    {
        "question": "What Linux command monitors a log file in real-time?",
        "options": [
            "cat -f /path/to/file.log",
            "tail -f /path/to/file.log",
            "grep -live /path/to/file.log",
            "watch file /path/to/file.log",
        ],
        "answer": "tail -f /path/to/file.log",
        "category": "API, SQL & Linux",
        "explanation": "tail -f follows the file and prints new lines as they are written.",
    },
    {
        "question": "What does chmod 755 mean?",
        "options": [
            "Read only for everyone",
            "Owner: rwx (7); Group: r-x (5); Others: r-x (5)",
            "Owner: rw (6); Group: r (4); Others: r (4)",
            "Full permissions for everyone (777)",
        ],
        "answer": "Owner: rwx (7); Group: r-x (5); Others: r-x (5)",
        "category": "API, SQL & Linux",
        "explanation": "chmod numbers: r=4, w=2, x=1. Add them per group: rwx=7, r-x=5, r--=4.",
    },
    # ─────────────────────────────────────────────
    # CATEGORY: Behavioral & Strategy
    # ─────────────────────────────────────────────
    {
        "question": "What is the best opening when asked 'How would you test X?' in an interview?",
        "options": [
            "Immediately list 20 test cases",
            "Ask 2-3 clarifying questions to understand the system before testing",
            "Say you need more time to think",
            "Start writing code",
        ],
        "answer": "Ask 2-3 clarifying questions to understand the system before testing",
        "category": "Behavioral & Strategy",
        "explanation": "Asking questions before testing is a core QA instinct and signals structured thinking.",
    },
    {
        "question": "What is the STAR method used for?",
        "options": [
            "Testing APIs",
            "Structuring behavioral interview answers about past experience",
            "Writing bug reports",
            "Planning test cases",
        ],
        "answer": "Structuring behavioral interview answers about past experience",
        "category": "Behavioral & Strategy",
        "explanation": "STAR = Situation + Task + Action + Result. Keep each answer under 90 seconds.",
    },
    {
        "question": "How should you handle being asked a technical question you don't know?",
        "options": [
            "Guess confidently",
            "Be honest, pivot to related knowledge, and show curiosity about learning it",
            "Change the subject",
            "Ask the interviewer for the answer",
        ],
        "answer": "Be honest, pivot to related knowledge, and show curiosity about learning it",
        "category": "Behavioral & Strategy",
        "explanation": "Intellectual honesty builds trust more than guessing. Pivot with what you DO know and show eagerness to learn.",
    },
    {
        "question": "Why are questions to the interviewer important?",
        "options": [
            "They are optional and rarely matter",
            "They signal genuine curiosity, preparation, and engagement with the role",
            "They demonstrate authority",
            "They are a chance to negotiate salary",
        ],
        "answer": "They signal genuine curiosity, preparation, and engagement with the role",
        "category": "Behavioral & Strategy",
        "explanation": "No questions = no curiosity = red flag. Questions show you're evaluating the role seriously.",
    },
    {
        "question": "When should you mention automation in a test plan response?",
        "options": [
            "Never mention it",
            "At the very beginning",
            "At the end, to show practical judgment — not as the first response",
            "Only if the job requires automation",
        ],
        "answer": "At the end, to show practical judgment — not as the first response",
        "category": "Behavioral & Strategy",
        "explanation": "Automation shows maturity — but only after you've demonstrated coverage and structure first.",
    },
    {
        "question": "What is the best structure for a 'Tell me about yourself' answer?",
        "options": [
            "Talk about your hobbies first",
            "Past (relevant background) → Present (current focus/skills) → Future (why this role)",
            "List all your technical skills",
            "Describe your education in detail",
        ],
        "answer": "Past (relevant background) → Present (current focus/skills) → Future (why this role)",
        "category": "Behavioral & Strategy",
        "explanation": "Structure = Past → Present → Future (60-90 seconds max). Always end on why this specific role.",
    },
    {
        "question": "How should you respond to the trap question 'Why leave development for QA?'",
        "options": [
            "'Development wasn't for me'",
            "'QA pays more'",
            "'I'm not leaving — I'm specializing. QA lets me apply full-stack understanding to guarantee quality.'",
            "'I had no choice'",
        ],
        "answer": "'I'm not leaving — I'm specializing. QA lets me apply full-stack understanding to guarantee quality.'",
        "category": "Behavioral & Strategy",
        "explanation": "Reframe QA as specialization, not a step down. Your engineering depth makes you a stronger QA engineer.",
    },
    {
        "question": "What should you do if you get stuck during a live coding interview?",
        "options": [
            "Stay silent and think hard",
            "Ask for the answer",
            "Slow down, narrate your thinking out loud, ask a clarifying question, try a simple example",
            "Switch programming languages",
        ],
        "answer": "Slow down, narrate your thinking out loud, ask a clarifying question, try a simple example",
        "category": "Behavioral & Strategy",
        "explanation": "Silence kills live interviews. Keep talking — even confusion expressed out loud is better than silence.",
    },
    {
        "question": "What is a good answer to 'The release is tomorrow and you find a critical bug. What do you do?'",
        "options": [
            "Delay the release unilaterally",
            "Ignore it if it seems minor",
            "Immediately escalate to the team, document the bug clearly, assess impact, and let the team decide on risk",
            "Fix it yourself without telling anyone",
        ],
        "answer": "Immediately escalate to the team, document the bug clearly, assess impact, and let the team decide on risk",
        "category": "Behavioral & Strategy",
        "explanation": "QA surfaces risk — the team decides. Show you're calm, clear, and team-oriented.",
    },
    {
        "question": "What does the interviewer learn from HOW you ask clarifying questions?",
        "options": [
            "How much you know about the product already",
            "Whether you think about context, risks, and users before testing — not just jumping in",
            "How fast you type",
            "Whether you've used Tufin before",
        ],
        "answer": "Whether you think about context, risks, and users before testing — not just jumping in",
        "category": "Behavioral & Strategy",
        "explanation": "Your questions reveal whether you think like a QA engineer naturally. Strong questions = strong signal.",
    },
    # ─────────────────────────────────────────────
    # CATEGORY: Tufin Scenario
    # ─────────────────────────────────────────────
    {
        "question": "You're shown Tufin's Permissions Manager screen. Before writing a test plan, what should you do FIRST?",
        "options": [
            "Start listing functional test cases immediately",
            "Ask clarifying questions: Who are the users? What actions are being tested? What's already covered?",
            "Write automated test code",
            "Ask the interviewer what the correct answer is",
        ],
        "answer": "Ask clarifying questions: Who are the users? What actions are being tested? What's already covered?",
        "category": "Tufin Scenario",
        "explanation": "Opening with clarifying questions demonstrates structured thinking and ensures your test plan covers the right scope.",
    },
    {
        "question": "What is the correct order for structuring a test plan for a new Tufin feature?",
        "options": [
            "Write edge cases → happy path → performance → security",
            "Scope & clarification → happy path → negative/edge cases → boundary values → permissions → performance → security",
            "Security → performance → happy path → UI checks",
            "Write automation scripts first, then fill in manual tests",
        ],
        "answer": "Scope & clarification → happy path → negative/edge cases → boundary values → permissions → performance → security",
        "category": "Tufin Scenario",
        "explanation": "Starting with scope prevents wasted effort. The happy path provides the baseline; edge cases and non-functional tests build on top of it.",
    },
    {
        "question": "You're writing a test plan for Tufin's Permissions Manager (RBAC). What is the MOST critical test type to include?",
        "options": [
            "UI layout and color theme checks",
            "Negative authorization tests — verifying that restricted roles are blocked at BOTH the UI and API level",
            "Performance tests under high user load",
            "Localization tests for multiple languages",
        ],
        "answer": "Negative authorization tests — verifying that restricted roles are blocked at BOTH the UI and API level",
        "category": "Tufin Scenario",
        "explanation": "In a security product, access control failures are critical severity. A Viewer role that can modify a firewall rule via API bypass is a serious vulnerability.",
    },
    {
        "question": "You're testing Tufin's Firewall Event Log. Which edge case is MOST important to include in your test plan?",
        "options": [
            "Checking that column headers display correctly",
            "Testing that the log correctly captures events at exactly midnight (day boundary) and across timezone edge cases",
            "Verifying that the export button has the correct color",
            "Testing with exactly 5 log entries",
        ],
        "answer": "Testing that the log correctly captures events at exactly midnight (day boundary) and across timezone edge cases",
        "category": "Tufin Scenario",
        "explanation": "Logs straddling day/timezone boundaries are a common source of silent data loss or duplication. In security products, missing events at boundaries can mean missed incidents.",
    },
    {
        "question": "You're testing an audit trail feature that records all admin changes to firewall rules. What properties MUST you verify?",
        "options": [
            "That the audit trail looks good visually and loads quickly",
            "Immutability (cannot be edited/deleted), completeness (every change is captured), accuracy (correct user/timestamp/change), and tamper-evidence",
            "That entries can be sorted alphabetically",
            "That only Admin role users can view the audit trail",
        ],
        "answer": "Immutability (cannot be edited/deleted), completeness (every change is captured), accuracy (correct user/timestamp/change), and tamper-evidence",
        "category": "Tufin Scenario",
        "explanation": "An audit trail that can be modified or that misses events is worse than no audit trail — it creates false confidence in a security-critical system.",
    },
    {
        "question": "What is the MOST important test to verify that a 'Viewer' role cannot modify firewall rules?",
        "options": [
            "Confirm the Edit button is hidden in the UI for Viewer role users",
            "Send a direct API PUT/POST request as a Viewer-role user and confirm the server returns HTTP 403 Forbidden",
            "Check that the Viewer role's name is displayed correctly in the UI",
            "Log in as Viewer and verify the read-only dashboard loads",
        ],
        "answer": "Send a direct API PUT/POST request as a Viewer-role user and confirm the server returns HTTP 403 Forbidden",
        "category": "Tufin Scenario",
        "explanation": "Hiding a button is a UI control, not a security control. The backend MUST reject unauthorized requests independently. Always test RBAC at the API level.",
    },
    {
        "question": "You're testing Tufin's Detection & Response dashboard. What metric is MOST important for verifying reliability?",
        "options": [
            "The color scheme of the severity indicators",
            "Data consistency — the total alert count must exactly equal the sum of Open + Acknowledged + Closed alerts",
            "That the page loads in under 10 seconds",
            "That the dashboard has a dark mode option",
        ],
        "answer": "Data consistency — the total alert count must exactly equal the sum of Open + Acknowledged + Closed alerts",
        "category": "Tufin Scenario",
        "explanation": "A security dashboard that shows incorrect totals gives analysts a false picture of the threat landscape. Data integrity is the most critical property of any monitoring tool.",
    },
    {
        "question": "You're performance testing firewall rule installation in Tufin. What is the most important threshold to establish?",
        "options": [
            "The maximum number of admin users who can log in simultaneously",
            "The maximum acceptable time to install a policy to a gateway under a realistic large rule base (e.g., 5,000 rules) — and whether performance degrades gracefully",
            "The file size of the exported policy package",
            "The rendering speed of the SmartConsole UI",
        ],
        "answer": "The maximum acceptable time to install a policy to a gateway under a realistic large rule base (e.g., 5,000 rules) — and whether performance degrades gracefully",
        "category": "Tufin Scenario",
        "explanation": "In production, policy install latency directly affects how quickly security changes take effect. Slow installs in enterprise environments with thousands of rules can be a critical operational issue.",
    },
    {
        "question": "Tufin releases a new UI feature for filtering firewall rules. When should you use manual testing vs. automated testing?",
        "options": [
            "Always use manual testing for UI features — automation is only for APIs",
            "Always automate everything immediately after the feature is built",
            "Manual testing for exploratory/UX validation and new feature coverage; automation for stable regression flows that run on every release",
            "Only automate if a test takes more than 1 hour to run manually",
        ],
        "answer": "Manual testing for exploratory/UX validation and new feature coverage; automation for stable regression flows that run on every release",
        "category": "Tufin Scenario",
        "explanation": "New UI features benefit from exploratory manual testing first. Once the feature stabilizes, core regression scenarios should be automated to catch regressions on every build.",
    },
    {
        "question": "During a live test plan exercise, you write a test case and the interviewer challenges it: 'Why would you test that?' What is the ideal response?",
        "options": [
            "Immediately agree and remove the test case",
            "Defend it aggressively — you wrote it, so it must be right",
            "Calmly explain your reasoning (risk, user impact, or edge case coverage), then genuinely consider their feedback and adjust if their point is valid",
            "Say 'I'm not sure' and move on",
        ],
        "answer": "Calmly explain your reasoning (risk, user impact, or edge case coverage), then genuinely consider their feedback and adjust if their point is valid",
        "category": "Tufin Scenario",
        "explanation": "Interviewers often challenge to test your reasoning, not to tell you that you're wrong. Defend with logic, stay open to feedback, and demonstrate collaborative thinking — a key QA trait.",
    },
]

ALL_CATEGORIES = sorted(list(set(q["category"] for q in QUESTIONS)))
